language: python
os:
    - osx
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - brew install chromedriver
script: cd Orbital_django; python manage.py test
notifications
    email:
        on_success: never
        on_failure: never

