language: python
os: osx
python:
    - "2.7"
before_install:
    - brew install chromedriver
install:
    - pip install -r requirements.txt
script: cd Orbital_django; python manage.py test
notifications:
    email:
        on_success: never
        on_failure: never

