os: osx
language: objective-c

sudo: false
dist: trusty

addons:
    chrome: beta
before_install:
    - brew install chromedriver
install:
    - pip install -r requirements.txt

script: if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; cd Orbital_django; python manage.py test )& fi

notifications:
    email:
        on_success: never
        on_failure: never



