language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install chromium-chromedriver; sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
install:
    - pip install -r requirements.txt
script: cd Orbital_django; python manage.py test
notifications:
    email:
        on_success: never
        on_failure: never

