language: python
os: linux
sudo: required
addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
install:
    - pip install -r requirements.txt
script: cd Orbital_django; python manage.py test
notifications:
    email:
        on_success: never
        on_failure: never

