language: objective-c
os: osx
before_install:
    - brew update
    - brew install chromedriver
addons:
    apt:
        packages:
            - google-chrome-stable
install:
    - pip install -r requirements.txt
script: cd Orbital_django; python manage.py test
notifications:
    email:
        on_success: never
        on_failure: never
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start &
    - sleep 3

