language: objective-c
os: osx
before_install:
    - brew udpate
    - brew install chromedriver
install:
    - pip install -r requirements.txt
script: cd Orbital_django; python manage.py test
notifications:
    email:
        on_success: never
        on_failure: never

