os: osx
language: objective-c

sudo: false
dist: trusty

addons:
    chrome: beta
before_install:
    - brew install chromedriver
install:
    - pip install -r requirements.txt

script: sudo Xvfb :99 -ac -screen 0 1024x768x8; export DISPLAY=:99.0; cd Orbital_django; python manage.py test

notifications:
    email:
        on_success: never
        on_failure: never



