language: objective-c
os: osx
dist: trusty
sudo: false
 
addons:
 apt:
    packages:
      - google-chrome-stable
 
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
before_install:
    - brew install chromedriver
install:
    - pip install -r requirements.txt
script: cd Orbital_django; python manage.py test
notifications:
    email:
        on_success: never
        on_failure: never



